package model

import (
	"fmt"
	"image-transporter/global"
	"image-transporter/utils"
)

func InitModel()  {
	autoMigrate()
}

func autoMigrate()  {
	if !global.DB.Migrator().HasTable(&Users{}){
		global.DB.AutoMigrate(&Users{})
		addBaseDataForUsers()
	}
}

func addBaseDataForUsers()  {
	randomPassword := utils.RandomStr(20) //pvCjyfhrfq8+mYxGD+(p    This is a random password generated during testing
	user := Users{
		UserName: "admin",
		Password: randomPassword,
		Permission: "admin",
	}
	fmt.Println("\nThe following are the default administrator account and password generated by the program initialization.")
	fmt.Printf("\nUserName:\t%s\nPassword:\t%s\nPlease record them in $ADMIN_USERNAME and $ADMIN_PASSWORD !!!\n\n", user.UserName, user.Password)
	if err := user.AddUser(); err != nil {
		utils.PrintfErr("add admin user faild.", err)
	}
}